### ISSUE TITLE
[Doc] RPM upload fail

### ISSUE THREAD

**Issue by nmenant** [f5devcentral/f5-declarative-onboarding#3]
BIG-IP version: 13.1.0.5

I used this doc to push the RPM on my BIG-IP: [RPM upload](https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/installation.html)

The following fails: 

`
LEN=$(wc -c $FN | cut -f 1 -d ' ')
`
`
curl -kvu $CREDS https://$IP/mgmt/shared/file-transfer/uploads/$FN -H 'Content-Type: application/octet-stream' -H "Content-Range: 0-$((LEN - 1))/$LEN" -H "Content-Length: $LEN" -H 'Connection: keep-alive' --data-binary @$FN
`

that's an extract of the output i got: 

`
< HTTP/1.1 400 Bad Request
< Date: 27 Nov 2018 13:34:35 UTC
`

**Comment by seattlevine** [comment]
These directions are somewhat specific to Linux platforms.
Can you verify that $LEN, $CREDS, and $IP are what you expect?

**Comment by nmenant** [comment]
Hi,

Sorry i missed your reply... 

Ok so i had time to do some more testing: 

the issue is the command LEN=$(wc -c $FN | cut -f 1 -d ' ') running on MAC. When you run this, It creates an "empty" LEN

However using LEN=$(wc -c $FN | cut -f 2 -d ' ') works fine:

`PAR-ML-00026375:DO menant$ wc -c $FN | cut -f 2 -d ' '
`
`1412023
`
I tested on ubuntu and yes you need to use cut -f 1 -d ' ' but on my MAC i had to use cut -f 2 -d ' '

**Comment by JosephPJordan** [comment]
Thanks for the feedback, we've included this step for Mac users to the documentation for Declarative Onboarding v1.1.0, which should be released very shortly. Going to close this issue.
